name: Deploy to EB

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**' 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install Dependencies for Backend
        working-directory: backend
        run: npm install 
      
      - name: Run server.js to check for errors
        working-directory: backend
        run: |
          nohup node server.js & sleep 5
          curl --fail http://localhost:3001/health || exit 1
        env:
          NODE_ENV: production
      
      - name: Stop server after check
        working-directory: backend
        run: |
          pkill -f "node server.js"
      
      - name: Generate Deployment Package for Backend
        working-directory: backend 
        run: zip -r ../backend-build.zip ./*  
      
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_EB_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_EB_SECRET_ACCESS_KEY }}
          application_name: 'gradflow-node'
          environment_name: 'Gradflow-node-env'
          version_label: "v-${{ github.sha }}-${{ github.run_number }}"
          region: eu-west-2  
          deployment_package: backend-build.zip
